name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Upload build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Get latest tag
        id: latest-tag
        uses: wyrihaximus/github-action-get-previous-tag@v1

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          full_commit_message: "build: release ${{ steps.latest-tag.outputs.tag }}"
